CXX		 = nvcc
CXXFLAGS = -O3 -lcublas 

all: sgemm

%.o: %.cu
	$(CXX) $(CXXFLAGS) -c $< -o $@

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

sgemm: cublas.o getopt.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o sgemm_cublas.x $^

clean:
	rm -f *.o
